_wandb:
    value:
        cli_version: 0.21.0
        e:
            shxzvp9u9y0r6lhvdvirjt1nrre5mzid:
                args:
                    - --node-ip-address=10.18.20.39
                    - --node-manager-port=42713
                    - --object-store-name=/tmp/ray/session_2025-07-20_20-29-01_990553_4100517/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-07-20_20-29-01_990553_4100517/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=64122
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=53091
                    - --gcs-address=10.18.20.39:48076
                    - --session-name=session_2025-07-20_20-29-01_990553_4100517
                    - --temp-dir=/tmp/ray
                    - --webui=
                    - --cluster-id=3d3b07df4b3f60e9ef5527a1408414b3a4e81fc0f0de2fa24d816fbb
                    - --startup-token=31
                    - --worker-launch-time-ms=1753057745548
                    - --node-id=3c33c413771a42bdb32c6788e80c6b30a32a4892a18ab341f0a444c7
                    - --runtime-env-hash=-1624044036
                    - --enable-resource-isolation=false
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1082043183104"
                        used: "53911552"
                email: tianyu.18@intl.zju.edu.cn
                executable: /home/tl688/.conda/envs/verl/bin/python
                git:
                    commit: 2bd291e5494db03ba358ef279a334c2f0829b979
                    remote: https://github.com/volcengine/verl.git
                gpu: NVIDIA H200
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-6eb2f1a6-6a14-6337-32d3-9c71bd4d3f3f
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-0be4a02c-6b49-2225-1931-09070fb32034
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-59bccf9d-cd07-683d-663a-7dea018392d8
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-eaf750a9-946b-4367-c837-8eb3dc6f199f
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-84d956e4-029f-c118-5bab-fabb6976cd61
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-94ca84d3-28c3-91f2-c352-5ce73f197c93
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-d4ef5d20-331f-f8d5-2270-a7ba43b61c6b
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-0889fcbc-66bc-bfa0-b903-ad2a62ea1629
                host: a1126u11n01.mghpcc.ycrc.yale.edu
                memory:
                    total: "2164086370304"
                os: Linux-4.18.0-553.52.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /home/tl688/.conda/envs/verl/lib/python3.11/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.11.13
                root: /nfs/roberts/project/pi_hz27/tl688/verl
                slurm:
                    cluster_name: bouchet
                    conf: /var/lib/slurmconf/slurm.conf
                    cpus_on_node: "40"
                    cpus_per_task: "40"
                    gpus_on_node: "8"
                    gpus_per_node: "8"
                    gtids: "0"
                    hint: nomultithread
                    job_account: pi_hz27
                    job_cpus_per_node: "40"
                    job_end_time: "1753144132"
                    job_gid: "1019130"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_id: "239775"
                    job_name: pytorch
                    job_nodelist: a1126u11n01
                    job_num_nodes: "1"
                    job_partition: gpu_h200
                    job_qos: normal
                    job_start_time: "1753057732"
                    job_uid: "19130"
                    job_user: tl688
                    jobid: "239775"
                    localid: "0"
                    mem_per_node: "163840"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: a1126u11n01
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /nfs/roberts/project/pi_hz27/tl688/verl
                    submit_host: login1.bouchet.ycrc.yale.edu
                    task_pid: "4100509"
                    tasks_per_node: "1"
                    threads_per_core: "1"
                    topology_addr: hdrspine.a1120u45.a1126u11n01
                    topology_addr_pattern: switch.switch.node
                    tres_bind: gres/gpu:verbose,closest
                    tres_per_task: cpu=40
                startedAt: "2025-07-21T00:33:50.756353Z"
                writerId: shxzvp9u9y0r6lhvdvirjt1nrre5mzid
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.51.1
            "12": 0.21.0
            "13": linux-x86_64
actor_rollout_ref:
    value:
        actor:
            checkpoint:
                contents:
                    - model
                    - optimizer
                    - extra
            clip_ratio: 0.2
            clip_ratio_c: 3
            clip_ratio_high: 0.2
            clip_ratio_low: 0.2
            entropy_coeff: 0
            fsdp_config:
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            grad_clip: 1
            kl_loss_coef: 0.01
            kl_loss_type: low_var_kl
            loss_agg_mode: token-mean
            optim:
                lr: 1e-06
                lr_warmup_steps: -1
                lr_warmup_steps_ratio: 0
                min_lr_ratio: 0
                num_cycles: 0.5
                total_training_steps: 340
                warmup_style: constant
                weight_decay: 0.01
            ppo_epochs: 1
            ppo_max_token_len_per_gpu: 16384
            ppo_micro_batch_size: null
            ppo_micro_batch_size_per_gpu: 8
            ppo_mini_batch_size: 128
            shuffle: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_dynamic_bsz: false
            use_kl_loss: true
            use_torch_compile: true
        hybrid_engine: true
        model:
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            lora_alpha: 16
            lora_rank: 0
            path: Qwen/Qwen2.5-VL-7B-Instruct
            target_modules: all-linear
            trust_remote_code: false
            use_fused_kernels: false
            use_liger: false
            use_remove_padding: true
            use_shm: false
        ref:
            fsdp_config:
                param_offload: true
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 8
            log_prob_use_dynamic_bsz: false
            strategy: fsdp
            ulysses_sequence_parallel_size: 1
            use_torch_compile: true
        rollout:
            disable_log_stats: true
            do_sample: true
            dtype: bfloat16
            enable_chunked_prefill: true
            enforce_eager: true
            engine_kwargs:
                sglang:
                    attention_backend: null
                    disable_cuda_graph: true
                    max_prefill_tokens: 8192
                    max_running_requests: 16
                    watchdog_timeout: 1800
                vllm:
                    swap_space: null
            free_cache_engine: true
            gpu_memory_utilization: 0.6
            ignore_eos: false
            layered_summon: false
            limit_images: 1
            load_format: dummy_dtensor
            log_prob_max_token_len_per_gpu: 16384
            log_prob_micro_batch_size: null
            log_prob_micro_batch_size_per_gpu: 8
            log_prob_use_dynamic_bsz: false
            max_model_len: null
            max_num_batched_tokens: 8192
            max_num_seqs: 1024
            mode: sync
            multi_turn:
                completion_callback: null
                enable: false
                format: chatml
                max_turns: null
                tool_config_path: null
            "n": 8
            name: sglang
            prompt_length: 1024
            response_length: 2048
            temperature: 1
            tensor_model_parallel_size: 2
            top_k: -1
            top_p: 1
            use_fire_sampling: false
            val_kwargs:
                do_sample: false
                "n": 1
                temperature: 0
                top_k: -1
                top_p: 1
algorithm:
    value:
        adv_estimator: grpo
        gamma: 1
        kl_ctrl:
            horizon: 10000
            kl_coef: 0.001
            target_kl: 0.1
            type: fixed
        kl_penalty: kl
        lam: 1
        norm_adv_by_std_in_grpo: true
        pf_ppo:
            reweight_method: pow
            weight_pow: 2
        use_kl_in_reward: false
        use_pf_ppo: false
critic:
    value:
        checkpoint:
            contents:
                - model
                - optimizer
                - extra
        cliprange_value: 0.5
        forward_max_token_len_per_gpu: 32768
        forward_micro_batch_size: null
        forward_micro_batch_size_per_gpu: null
        grad_clip: 1
        loss_agg_mode: token-mean
        model:
            enable_activation_offload: false
            enable_gradient_checkpointing: true
            external_lib: null
            fsdp_config:
                fsdp_size: -1
                offload_policy: false
                optimizer_offload: false
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            lora_alpha: 16
            lora_rank: 0
            path: ~/models/deepseek-llm-7b-chat
            target_modules: all-linear
            tokenizer_path: Qwen/Qwen2.5-VL-7B-Instruct
            trust_remote_code: false
            use_remove_padding: false
            use_shm: false
        optim:
            lr: 1e-05
            lr_warmup_steps_ratio: 0
            min_lr_ratio: null
            total_training_steps: 340
            warmup_style: constant
            weight_decay: 0.01
        ppo_epochs: 1
        ppo_max_token_len_per_gpu: 32768
        ppo_micro_batch_size: null
        ppo_micro_batch_size_per_gpu: null
        ppo_mini_batch_size: 128
        rollout_n: 8
        shuffle: false
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: false
custom_reward_function:
    value:
        name: compute_score
        path: .//verl/utils/reward_score/path.py
data:
    value:
        custom_cls:
            name: null
            path: null
        filter_overlong_prompts: true
        filter_overlong_prompts_workers: 1
        image_key: images
        max_prompt_length: 1024
        max_response_length: 2048
        prompt_key: prompt
        return_full_prompt: false
        return_raw_chat: false
        return_raw_input_ids: false
        reward_fn_key: data_source
        shuffle: true
        tokenizer: null
        train_batch_size: 128
        train_files:
            - path_reason_data_4tianyu/path_reason_mcqa_train.0.parquet
            - path_reason_data_4tianyu/path_reason_mcqa_train.12.parquet
            - path_reason_data_4tianyu/path_reason_mcqa_train.24.parquet
            - path_reason_data_4tianyu/path_reason_mcqa_train.36.parquet
            - path_reason_data_4tianyu/path_reason_mcqa_train.48.parquet
            - path_reason_data_4tianyu/path_reason_mcqa_train.60.parquet
            - path_reason_data_4tianyu/path_reason_mcqa_train.72.parquet
            - path_reason_data_4tianyu/path_reason_mcqa_train.84.parquet
        truncation: error
        trust_remote_code: false
        use_shm: false
        val_batch_size: 128
        val_files: path_reason_data_4tianyu/path_reason_mcqa_train.127.parquet
        validation_shuffle: false
        video_key: videos
ray_init:
    value:
        num_cpus: null
        timeline_json_file: null
reward_model:
    value:
        enable: false
        forward_max_token_len_per_gpu: 32768
        launch_reward_fn_async: false
        max_length: null
        micro_batch_size: null
        micro_batch_size_per_gpu: null
        model:
            external_lib: null
            fsdp_config:
                fsdp_size: -1
                param_offload: false
                reshard_after_forward: true
                wrap_policy:
                    min_num_params: 0
            input_tokenizer: Qwen/Qwen2.5-VL-7B-Instruct
            path: ~/models/FsfairX-LLaMA3-RM-v0.1
            trust_remote_code: false
            use_fused_kernels: false
            use_remove_padding: false
            use_shm: false
        reward_manager: naive
        sandbox_fusion:
            max_concurrent: 64
            url: null
        strategy: fsdp
        ulysses_sequence_parallel_size: 1
        use_dynamic_bsz: false
trainer:
    value:
        balance_batch: true
        critic_warmup: 0
        default_hdfs_dir: null
        default_local_dir: ../ckpt/checkpoints
        del_local_ckpt_after_load: false
        device: cuda
        experiment_name: pathtest1
        log_val_generations: 0
        logger:
            - console
            - wandb
        max_actor_ckpt_to_keep: null
        max_critic_ckpt_to_keep: null
        n_gpus_per_node: 8
        nnodes: 1
        project_name: testpath
        ray_wait_register_center_timeout: 300
        resume_from_path: null
        resume_mode: auto
        rollout_data_dir: ../ckpt/rollout_data
        save_freq: 40
        test_freq: -1
        total_epochs: 5
        total_training_steps: null
        val_before_train: false
        validation_data_dir: ../ckpt/validation_data
